### ISSUE TITLE
CMAKE can't find "osvrRenderManager", fails and build cannot proceed

### ISSUE THREAD

**Issue by isantop** [OSVR/SteamVR-OSVR#101]
## Description of issue

During the initial cmake run, the configuration fails with this error:

```
CMake Error at CMakeLists.txt:31 (find_package):
  By not providing "FindosvrRenderManager.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "osvrRenderManager", but CMake did not find one.

  Could not find a package configuration file provided by "osvrRenderManager"
  with any of the following names:

    osvrRenderManagerConfig.cmake
    osvrrendermanager-config.cmake

  Add the installation prefix of "osvrRenderManager" to CMAKE_PREFIX_PATH or
  set "osvrRenderManager_DIR" to a directory containing one of the above
  files.  If "osvrRenderManager" provides a separate development package or
  SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

Running cmake on Ubuntu 16.10 with cmake 3.5.2

## Steps to reproduce the problem

1. Install build requirements
2. Clone latest source from git master
3. make build dir, and cd in
4. Run "cmake .."

## System configuration

*Please specify any relevant system configuration information.*

  * **Graphics card(s)**: Nvidia GeForce GTX970m
  * **Operating system**: Ubuntu 16.10
  * **Version of SteamVR**: 1483489013
  * **Version of SteamVR-OSVR**: git-master

## Attached files

*Please attach the following files:*

  * *The `osvr_server` configuration file.*

[osvr_server_config.json.txt](https://github.com/OSVR/SteamVR-OSVR/files/685648/osvr_server_config.json.txt)

**Comment by godbyk** [comment]
When you run CMake, either set `CMAKE_PREFIX_PATH` or `osvrRenderManager_DIR` appropriately (as mentioned in the error message).  For example:

```bash
$ cmake .. -DCMAKE_PREFIX_PATH=~/osvr
```

It's easiest to set `CMAKE_PREFIX_PATH` to the installation prefix used for all the OSVR components (server, RenderManager, etc.) so you don't have to set individual `_DIR` variables.

**Comment by isantop** [comment]
Sorry, I'm new to OSVR. What is the appropriate directory? The location where the OSVR components are _installed_ (on my system they're in /usr/local) or the location of the _source code_? Or is this somewhere else entirely?

**Comment by godbyk** [comment]
Where they're installed (e.g. `/usr/local`).

**Comment by isantop** [comment]
After setting that variable, I'm still getting the same error trying to build the components.

**Comment by isantop** [comment]
I also tried re-installed the OSVR-CORE to a directory in my home folder (`~/osvr`) and CMAKE still fails with the same error.

**Comment by godbyk** [comment]
Post your `CMakeCache.txt` file and I'll take a look. (It'll be in the build directory.)

**Comment by isantop** [comment]
[CMakeCache.txt](https://github.com/OSVR/SteamVR-OSVR/files/685775/CMakeCache.txt)

Attached, thanks!

**Comment by godbyk** [comment]
Have you built and installed OSVR RenderManager? What are the contents of the `~/osvr/lib/cmake/` directory?

**Comment by isantop** [comment]
I came to that conclusion as well, and have tracked down and built RenderManager. CMAKE is now completing successfully. However, `make` fails with:

```
/usr/bin/ld: ../vendor/OSVR-Display/osvr/Display/libosvrDisplay_static.a(Display.cpp.o): relocation R_X86_64_PC32 against symbol `_ZNK4osvr7display11DisplaySizeeqERKS1_' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

**Comment by godbyk** [comment]
That should be fixed in the current OSVR-Display repository. If you change to the `vendor/OSVR-Display` directory and run `git checkout master`, then go back to the build directory and rerun `make`, does it work?

**Comment by isantop** [comment]
Did that, now it fails on `Building CXX object vendor/OSVR-Display/osvr/Display/CMakeFiles/osvrDisplay.dir/Display.cpp.o`

**Comment by isantop** [comment]
Here's the traceback: http://pastebin.ubuntu.com/23741282/

**Comment by godbyk** [comment]
The `invalid_argument` error was a bug on my part (forgot to `#include` a header). I've just pushed a fix for it. If you go to the `vendor/OSVR-Display` directory and run `git pull` it should grab the update.

**Comment by isantop** [comment]
Thanks, I think it worked that time. I'll have to check out if it's all running tomorrow when I get back to work (where the OSVR HDK is located right now), but I'll report back if I run into any issues.

Thanks again!

**Comment by isantop** [comment]
Sorry to bug again. Everything has now compiled and appears to be working, however TF2 won't let me enable VR mode, telling me that the headset was not detected. 

Steps:
1. Plug in hardware
2. start `osvr_server` with the default configuration file
3. Open Steam, then select TF2 and open (using the -vr flag to enable the option in settings)
4. The VR mode option is now present in settings, but can't be enabled.

Checking with `vrcmd` in place of steps 3 and 4, I get the following error message:

VR_IsHmdPresent returned false to indicate that there are no attached HMDs.

The headset's listings are displayed in lsusb, and the headset works correctly when running a non-steam VR-compatible game. There is additional output from the osvr_server window.

Any ideas?

**Comment by Balderick** [comment]
Have you tried the openvr legacy_title option?

**Comment by isantop** [comment]
Where do I select/configure that?

**Comment by godbyk** [comment]
@isantop Can you post a copy of the `vrserver.txt` log file?

**Comment by isantop** [comment]
I can't seem to find a copy of that file on my system. Where should it be located?

**Comment by isantop** [comment]
Found where the log is supposed to be, `~/.steam/logs/` but there is no vrserver.txt log there.

**Comment by isantop** [comment]
If I manually run `vrserver` in `steamapps/common/SteamVR/bin/linux64`, then I get this output in vrserver.txt:

```
Thu Jan 05 2017 16:02:23.924394 - ================================================================================================
Thu Jan 05 2017 16:02:23.924442 - ================================================================================================
Thu Jan 05 2017 16:02:23.924492 - VR server (v0) starting up with config=/home/ian/.steam/config
Thu Jan 05 2017 16:02:23.924554 - CIPCPipe::CreatePipe(VR_ServerPipe) bound to 54163
Thu Jan 05 2017 16:02:23.924886 - [Settings] Load Default Json Settings from /home/ian/.steam/steamapps/common/SteamVR/resources/settings/default.vrsettings
Thu Jan 05 2017 16:02:23.924953 - [Settings] Load Default Json Settings from /home/ian/.steam/steamapps/common/SteamVR/drivers/lighthouse/resources/settings/default.vrsettings
Thu Jan 05 2017 16:02:23.924996 - [Settings] Load Default Json Settings from /home/ian/.steam/steamapps/common/SteamVR/drivers/null/resources/settings/default.vrsettings
Thu Jan 05 2017 16:02:23.925231 - [Settings] Load Json Settings from /home/ian/.steam/config/steamvr.vrsettings
Thu Jan 05 2017 16:02:23.925296 - Unable to read app config file from /home/ian/.steam/config/appconfig.json. No applications will be available
Thu Jan 05 2017 16:02:24.107454 - [DriverManager] Create new Resource Driver Manager
Thu Jan 05 2017 16:02:24.107849 - Load Json firmware manifest from /home/ian/.steam/steamapps/common/SteamVR/drivers/lighthouse/firmware/manifest.vrfirmware
Thu Jan 05 2017 16:02:44.109782 - Shutting down server after 20.002329 seconds of idleness
Thu Jan 05 2017 16:02:44.109875 - VR server shutting down
Thu Jan 05 2017 16:02:44.145489 - Listener thread ending
```

**Comment by godbyk** [comment]
I don't see anything in there about loading the SteamVR-OSVR driver.  Do you have the driver registered with `vrpathreg`?

**Comment by isantop** [comment]
I hadn't yet, however after doing that I'm still having this problem. I've attached the output of `vrpathreg show`, `vrserver`, the contents of `vrserver.txt` and the output of `vrcmd`

[steamvr-outputs.txt](https://github.com/OSVR/SteamVR-OSVR/files/690348/steamvr-outputs.txt)

**Comment by godbyk** [comment]
Check the `steamvr.vrsettings` file. Make sure you don't have an extra comma or something. (Note the parse error in the `vrserver.txt` file.)

**Comment by isantop** [comment]
Finally tracked down the problem with the vrsettings file. Still getting issues with osvr not detecting an HMD. vrserver.txt attached.

[Web-viewable](http://pastebin.ubuntu.com/23754835/)
[vrserver.txt](https://github.com/OSVR/SteamVR-OSVR/files/691025/vrserver.txt)

**Comment by godbyk** [comment]
I ran into this error `Driver attempted to add invalid tracked device` with the beta version of SteamVR and an older version of the OSVR driver yesterday. That's one of the things that the new driver fixes.

Are you running the latest version of the SteamVR-OSVR driver (i.e., the code from the `master` branch as of yesterday evening)?

**Comment by isantop** [comment]
The latest code from `master` fails to build. Errors [here](http://pastebin.ubuntu.com/23770945/)

**Comment by godbyk** [comment]
Did you run `git submodule update` to get the latest openvr code?

**Comment by isantop** [comment]
Yep, same errors

**Comment by isantop** [comment]
So, I tracked down the problem with the build to a problem with Case-sensitive filesystems. I corrected that problem and submitted a PR to get it working. 

Now when I run vrcmd, I get [this output](http://pastebin.ubuntu.com/23772525/)

However, TF2 still doesn't list any HMDs compatible with the game.
