### ISSUE TITLE
IL2BOS Horizontal and vertical FOV does not match with HDK2/steamOSVR

### ISSUE THREAD

**Issue by lefufu** [OSVR/SteamVR-OSVR#115]
## Description of issue

 In Il2 BoS the horizontal and vertical FOV are not matching, Jauges are not circular and head rotation introduce tearing instead of view rotation. The game is working well in VR with Vive and Rift.

My config is working without trouble with DCS world and war thunder.
I opened a ticket at Il2 support site, they answered that the problem is on headset provider side...

Same problem with extended or direct mode, and a new empty steamvr.setting file. Tested with beta and no beta steamVR version. Tested with 0.7.0, 0.8.0 AIO installer and the build 356 of OSVR core.

Other people have posted the same problem on Il2 Bos forums.

## Steps to reproduce the problem
*How can the problem be reproduced?*
just use Il2 Bos and a HDK2 !

 ## System configuration
*Please specify any relevant system configuration information.*

  * **Graphics card(s):** gtx 1070
  * **Operating system:** win 10 64b
  * **Version of SteamVR**: latest beta version
  * **Version of SteamVR-OSVR:** 0.8.0 installer.

## Attached files
*Please attach the following files:*

  * *The `osvr_server` configuration file.*
I added the default 0.8.0 config file that I use now
[osvr_config_HDK_2_default.zip](https://github.com/OSVR/SteamVR-OSVR/files/974545/osvr_config_HDK_2_default.zip)

  * *The `vr*.txt` files from the Steam `logs` directory.*
I added the report of steamVr, a picture of in game steamVR miror illustrating the FOV problem. 
[OSVR_HDK2_PB.zip](https://github.com/OSVR/SteamVR-OSVR/files/974544/OSVR_HDK2_PB.zip)

**Comment by godbyk** [comment]
The SteamVR-OSVR driver gets its FOV information from the OSVR server.

If you want to try adjusting the FOV values, you may do so in the [`displays/OSVR_HDK_2_0.json` file](https://github.com/OSVR/OSVR-Core/blob/master/apps/displays/OSVR_HDK_2_0.json#L13).

Documentation for the FOV parameters in that file may be found [here](https://github.com/OSVR/OSVR-JSON-Schemas/blob/master/doc/display_descriptor_schema_v1/Structure%20of%20JSON%20descriptor%20file%20for%20HMDs.md).

**Comment by lefufu** [comment]
I tried different FOV settings in the OSVR_HDK_2_0.json file but did not manage to change the problem. The The view was still deformed, but in different way...

**Comment by lefufu** [comment]
On forum, it looks like Pimax users had the same problem, but also that the last "piplay" version (software suite of pimax) fixed them...

**Comment by lefufu** [comment]
Is there something that can be done ? This game is still unplayable with the HDK2...

**Comment by lefufu** [comment]
oops, I closed by mistake this issue !

**Comment by lefufu** [comment]
same as 118
