### ISSUE TITLE
Disbale, Remove Or Uninstall OSVR Camera In SteamVR

### ISSUE THREAD

**Issue by Balderick** [OSVR/SteamVR-OSVR#117]
SteamVR-OSVR 342 driver brought a lot of annoying juddering and bouncing to my steamvr experience which was not apparent with older driver versions.

I use models, backgrounds, environments and other customisations for steamvr from steam workshop and have found the osvr camera thing to be nothing but annoying as it behaves well short of any other steamvr customisation that I choose to implement.  It even shows up when and where it should not like when steamvr dashboard is activated and interferes with other customisations from steamvr workshop.   This is a very poorly implemented steamvr feature which I would really like to get rid of.

Also, I am adding steamvr tracking to my osvr hdk hmd so the osvr ir camera model is unsuitable and irrelevant to my setup.

How do I disable, remove or uninstall the osvr camera model that detrimentally interferes with my steamvr experiences?

**Comment by godbyk** [comment]
Set the `cameraRenderModel` value in the `steamvr.vrsettings` file.

To use a model within the SteamVR-OSVR driver's `resources/rendermodels` folder, use the `{osvr}` prefix followed by the base name of the `.obj` filename.
To use a model installed in SteamVR's `resources/rendermodels` folder instead, omit the `{osvr}` prefix and just use the basename of the model file.

Default: `{osvr}osvr_camera`

**Comment by Balderick** [comment]
This is what my steamvr.vrsettings look like sfter subscribing to workshop itemsand then selecting them through steamvr dashboard settings for steamvr customisation.

```{
   "modelskins" : {
      "generic_tracker" : "C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\250820\\674789170\\untitled\\untitled.obj",
      "generic_tracker_PublishedFileId" : "674789170"
   },
   "steamvr" : {
      "background" : "C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\250820\\651313380\\Universe_seamless.png",
      "defaultMirrorView" : 1,
      "enableHomeApp" : false,
      "mirrorViewGeometry" : "1447 603 960 1080",
      "showMirrorView" : true
   }
}

```

The changes for latest commit specify default.vrsettings as the file being used to initiate the osvr camera in steamvr compositor.

How do i simply stop the osvr camera being shown without uninstalling osvr driver?

It is interfering with the content from steamvr workshop, steamvr home, steamvr apps and steamvr dashboard.

I am asking how to completely remove or disable osvr camera render model.  I am currently trying to use this camera model `"modelskins" : {
      "generic_tracker" : "C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\250820\\674789170\\untitled\\untitled.obj",
      "generic_tracker_PublishedFileId" : "674789170"` but the osvr camera still gets renedered and interferes with this and other steamvr workshop items.


Could the sharing of osvr camera model through steamvr workshop help with integrating it into steamvr better?     
The pulsating judder and bouncing is unique to when osvr camera rendermodel is being rendered no other steamvr customisation does this.

Does this look like openvr bug?   i.e. after starting steamvr with the {osvr} rendrmodel selecting workshop camera should tell steamvr to forget about the {osvr} rendermodel

**Comment by Balderick** [comment]
Now think what I am trying to describe is more of an openvr/steamvr issue and is related to https://github.com/OSVR/OSVR-Core/issues/530 so can close this for now.
