### ISSUE TITLE
Problem with ViveDisplayExtractor.exe and display

### ISSUE THREAD

**Issue by ghost** [OSVR/SteamVR-OSVR#122]
hello,
i'm developer and i want to use from steamvr osvr plugin but when i'm using from ViveDisplayExtractor.exe it doesn't generate display files ,and this is output :

> July 11 13:40:08.307 info [OSVR]: Logging for C:\Program Files\OSVR\SDK\x64\bin\
> ViveDisplayExtractor.exe
> July 11 13:40:08.374 info [ServerDriverHost]: TrackedDeviceAdded(LHR-D6B76217)
> 
> [DisplayExtractor] Device with s/n LHR-D6B76217 activated, assigned ID 0
> [DisplayExtractor] Got 1 tracked devices at startup
> [DisplayExtractor] -- it's a display, too! We'll extract its display parameters
> now.
> Error trying to read the manufacturer of the attached HMD...
> Error trying to read the model of the attached HMD...
> [getStringProperty] Got an initial return value larger than the buffer size: ret
>  = 4075540368, buf.size() = 32
> [getStringProperty] THIS SHOULDN'T HAPPEN: Got a return value larger than the bu
> ffer size: ret = 4075540368, buf.size() = 32
> Error trying to read the serial number of the attached HMD...
> 
> [DisplayExtractor]
> 
> 
> [DisplayExtractor] Successfully extracted display parameters from Vive.
> 
> [DisplayExtractor] Writing distortion mesh data file:
> C:/Program Files/OSVR/SDK/x64/bin/displays/HTC_Vive_meshdata.json
> 
> [DisplayExtractor] Writing display descriptor file:
> C:/Program Files/OSVR/SDK/x64/bin/displays/HTC_Vive.json
> 
> [DisplayExtractor] Be sure to re-run this tool if you move your OSVR Server inst
> allation, as the generated files include absolute paths.
> [DisplayExtractor] Press enter to quit...
> 
 
and in cpp context when i insert this code : 
		osvr::renderkit::RenderManager* render =
			osvr::renderkit::createRenderManager(context.get(), "OpenGL");

then i have display error problem : 

> error [createRenderManager]: Got Display info from server (
> ignore earlier errors that occured while we were waiting to connect)
...

> July 11 13:55:29.058 error [createRenderManager]: Could not parse /display strin
> g from server.

my system info:
_Graphics card: Gigabyte Geforce gtx 1070
Graphic Driver version : 384.76
Operating system: windows 8.1
Version of SteamVR : 1499136050
VR Device: HTC Vive_

how can i solve this problem?

**Comment by godbyk** [comment]
Hello, @masoudrk95.

Please file this issue in the [OSVR-Vive repository](https://github.com/osvr/OSVR-Vive).

The SteamVR-OSVR repository is for using OSVR-supported HMDs with SteamVR.

Thanks!
