### ISSUE TITLE
ART-Flystick as controller in SteamVR ?

### ISSUE THREAD

**Issue by pzeth** [OSVR/SteamVR-OSVR#129]
Hello,

I wonder if it is possible to use an ART-Flystick as a controller in SteamVR.

I have one ART-Flystick connected to OSVR-server via OSVR-ART plugin at /me/hands/right.
The Flystick shows up in the OSVRTrackerView display, so the setup looks OK up to this point.
Also, any pressed Flystick button is identified by DTrack UI (so, yes, radio works).

But within SteamVR-Home, or any other SteamVR-app, no representation of a controller is visible.
Pressing Flystick buttons has no effect in-game.

So is using ART-Flysticks as substitutes for Vive-Controllers currently possible ?  If so, how ?
Thanks in advance for any hints.

Peter

System:
- Win10, GTX 1080
- OSVR / OSVR-SteamVR installation via HDK_Windows_Installer_Beta_0.8.0.0.exe
- SteamVR 1510619449

Files:
[osvr_server_config.ART-fly2+atc.2.json.txt](https://github.com/OSVR/SteamVR-OSVR/files/1479175/osvr_server_config.ART-fly2.atc.2.json.txt)
[osvr-output.txt](https://github.com/OSVR/SteamVR-OSVR/files/1479168/osvr-output.txt)
[steamvr-logs.zip](https://github.com/OSVR/SteamVR-OSVR/files/1479169/steamvr-logs.zip)

**Comment by godbyk** [comment]
SteamVR-OSVR doesn't yet support controllers. There has been some preliminary work done to add controller support, however. The progress of this is tracked in #30.
