### ISSUE TITLE
Tracking and/or projection is incorrect.

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/SteamVR-OSVR#22]
I'm not sure what's going on with the tracking and/or projection, but it appears to be incorrect:

![image](https://cloud.githubusercontent.com/assets/320332/12211885/6f72655c-b632-11e5-852f-2c40457171b4.png)

One eye seems flipped form the other, but also rotations seem to be in the wrong plane (as if one or more of pitch/yaw/roll were swapped). Also I thought I remember this compositor screen being a sphere, not two planes with a grid on them. Is it a squashed sphere?

**Comment by d235j** [comment]
This is new — and strange as the JMonkeyVR example works properly.
The projection matrices are already somewhat bogus due to https://github.com/OSVR/OSVR-Core/issues/249 but it should not be this bad!
