### ISSUE TITLE
Use window position from DisplayConfig

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/SteamVR-OSVR#23]
Currently the code uses a hard-coded window position of x: 1920, y: 0 which only works if your main monitor is width 1920. The DisplayConfig from the OSVR server has this position, and we should read it.

Unfortunately the position isn't exposed by at least the C++ API (I haven't checked the C API), so this issue is blocked until it's available.

**Comment by d235j** [comment]
We probably just need to add the API call to the C++ API (and the C API if it isn't there yet). I can take a look at doing this.

**Comment by d235j** [comment]
@JeroMiya: where does the DisplayConfig have this position? I looked and didn't see it all that readily.

**Comment by russell-taylor** [comment]
If we can use RenderManager for steam, it will tell you this information.

**Comment by d235j** [comment]
@russell-taylor I'm sure we can but that wouldn't help us on non-Windows platforms right?

**Comment by russell-taylor** [comment]
If you don't need DirectMode, it should be able to compile using OpenGL on at least Linux and Mac.  I don't know about Android.  It handles time warp and distortion correction in addition to figuring out the basic rendering setup.

**Comment by d235j** [comment]
Do we have source for the non-Direct Mode part? I wouldn't mind trying to compile it but I am aware of the issues with the vendor APIs for Direct Mode.

**Comment by JeroMiya** [comment]
I was mistaken. It's not in the DisplayConfig object, but the renderManagerConfig object. Fortunately, the RenderManagerConfig parser was moved to OSVR-Core and is available for us to use.

It's a header-only C++ class - no C API. We'll need to add jsoncpp to our dependencies however.

**Comment by russell-taylor** [comment]
@d235j It has been added to my queue to split out the non-vendor-NDA parts of RenderManager so we can release them.  We're in the middle of a three-way merge of features, so I'll want to wait until that happens before doing the split.

**Comment by d235j** [comment]
@russell-taylor great! It will be nice to be able to begin porting RenderManager to other platforms.
