### ISSUE TITLE
SteamVR Games Crashing with Unknown VRMsgType (1701841162)

### ISSUE THREAD

**Issue by trevorirwin** [OSVR/SteamVR-OSVR#31]
Some SteamVR games - in this case, the popular Windlands - are crashing to desktop randomly. Sometimes after a minute of playing, sometimes after several. I am not sure if the crashes I'm experiencing in Windlands are related to those in Elite: Dangerous, which seem to happen less frequently, but in the same way: the game closes silently followed by the compositor shutting down moments later and SteamVR either closing silently or attempting to close and hanging. I will acquire a log after an Elite crash as soon as I have time to run into one again.

Below is the log from SteamVR after a Windlands crash, where the 3rd line is the most relevant. Note the 309MB payload! Whatever this message is, it's causing the game to crash. I am not completely sure the issue is caused by the SteamVR-OSVR plugin, but I was hoping those here might be able to discern if it is. If so, perhaps we can discover what this message type is and how to fix it.

```
Fri Jan 22 2016 20:01:47.921 - New Connect message from G:\Steam\steamapps\common\Windlands\Windlands_Win_x64_SteamVR\Windlands_Win_x64_SteamVR.exe 2024
Fri Jan 22 2016 20:01:47.921 - Using existing HMD osvr.OSVR HMD
Fri Jan 22 2016 20:02:38.819 - Unknown message type Unknown VRMsgType (1701841162) (309027685 byte payload) from vrmonitor (3116)
Fri Jan 22 2016 20:02:38.819 - Processing message Unknown VRMsgType (1701841162) from vrmonitor (3116) took 0.11 seconds
Fri Jan 22 2016 20:02:38.819 - Process vrmonitor (3116) disconnected
Fri Jan 22 2016 20:02:38.819 - Quitting all OpenVR processes because master process 3116 disconnected
Fri Jan 22 2016 20:02:38.820 - Sending Quit event to process vrmonitor (3116)
Fri Jan 22 2016 20:02:38.820 - Sending Quit event to process vrdashboard (4912)
Fri Jan 22 2016 20:02:38.820 - Sending Quit event to process Windlands_Win_x64_SteamVR (2024)
Fri Jan 22 2016 20:02:38.849 - IPCPipe(Windlands_Win_x64_SteamVR (2024)): Process disconnected.
Fri Jan 22 2016 20:02:38.849 - Process Windlands_Win_x64_SteamVR (2024) disconnected
Fri Jan 22 2016 20:02:40.237 - IPCPipe(vrdashboard (4912)): Process disconnected.
Fri Jan 22 2016 20:02:40.237 - Process vrdashboard (4912) disconnected
Fri Jan 22 2016 20:02:40.248 - Sending Quit event to process vrcompositor (7228)
Fri Jan 22 2016 20:02:40.996 - AppTransition: Aborting external launch because of timeout after 0.00199437 seconds
Fri Jan 22 2016 20:02:40.996 - Aborting launch of ''
Fri Jan 22 2016 20:02:45.258 - Kill process vrcompositor (7228) because it didn't quit in time
[^^^This line repeats a few dozen times]
Fri Jan 22 2016 20:02:45.934 - IPCPipe(vrcompositor (7228)): Process disconnected.
Fri Jan 22 2016 20:02:45.934 - Process vrcompositor (7228) disconnected
Fri Jan 22 2016 20:02:45.943 - VR server shutting down
Fri Jan 22 2016 20:02:46.008 - Listener thread ending
```

**Comment by godbyk** [comment]
We've just released an updated SteamVR-OSVR driver that should work with the current release of SteamVR. Please give it a try and report back if you encounter any problems.

**Comment by godbyk** [comment]
I'm closing this issue due to a lack of information. If you are the original filer of this issue and still encounter this problem, feel free to reopen this issue. If you're not the original filer of this issue, please open a new issue instead.

**Comment by trevorirwin** [comment]
The problem appears to have been resolved; thanks for closing the issue.

**Comment by godbyk** [comment]
I'm glad to hear that! Thanks for letting me know.
