### ISSUE TITLE
osvr_reset_yaw resets yaw and translation axes in OSVR Tracker View but not in SteamVR apps

### ISSUE THREAD

**Issue by trevorirwin** [OSVR/SteamVR-OSVR#32]
I've found that the osvr_reset_yaw app distributed within OSVR-core appears to successfully reset yaw and the translation axes accordingly, but does not reset the translation axes in SteamVR. That is, the *rotation* is reset correctly in both Tracker View and SteamVR. However, in SteamVR only, the "forward" orientation is no longer the "forward" translational axis. For example, in Elite: Dangerous after resetting yaw I will be looking forward in the cockpit, but when I lean forward my view may move to the left - when I lean left it may move backwards.

I'm not entirely sure why I'm getting yaw drift in the first place as I'm under the impression that the IR camera should be used as an absolute reference for "forward", but that's another issue.

**Comment by godbyk** [comment]
We recently updated the SteamVR-OSVR plugin to allow it to complete room setup, enable direct mode, and experience improved tracking. Please try the latest version of the plugin with the latest released version of SteamVR and see if this resolves the problem.
