### ISSUE TITLE
Steam installs but window is off primary screen and overlaps onto OSVR HMD

### ISSUE THREAD

**Issue by CoolGames** [OSVR/SteamVR-OSVR#35]
HP Sprout is so non-standard that the display settings are not passed on to programs.
Steam runs off the right side of the primary screen where the OSVR HMD is located.
The HMD is in portrait and is difficult to setup properly.

**Comment by CoolGames** [comment]
[Steam Moved](http://www.sevenforums.com/tutorials/75291-offscreen-window-move-back-desktop.html] by this solution.
Distortion and mirroring still exists.

**Comment by JeroMiya** [comment]
I'm not sure about the distortion and mirroring issues. But if it helps the steam plugin uses the window position from the `renderManagerConfig` section of your server configuration. There is a `window` object under `renderManagerConfig` that has an `xPosition` field and a `yPosition` field. You can adjust those as needed to get the window to not overlap with the main screen, if your main screen is not 1080p as the default sample configs assume.

**Comment by godbyk** [comment]
@CoolGames Have you had a chance to try @JeroMiya's suggestion of adding the `renderManagerConfig` `xPosition` parameter to your configuration file?  Did it resolve the issue you were having?

**Comment by godbyk** [comment]
I'm closing this issue due to a lack of information. If you are the original filer of this issue and still encounter this problem, feel free to reopen this issue. If you're not the original filer of this issue, please open a new issue instead.
