### ISSUE TITLE
No "drivers" folder insize .zip file

### ISSUE THREAD

**Issue by mctaveesh** [OSVR/SteamVR-OSVR#36]
I downloaded the zip file and unzipped. I have no folder/directory named Drivers anywhere

**Comment by godbyk** [comment]
@mctaveesh We've just released an updated SteamVR-OSVR driver that should work with the current release of SteamVR. Please give it a try and report back if you encounter any problems.

If the zip file you download is still empty, please paste the URL here and I'll take a look.

Thanks!

**Comment by godbyk** [comment]
I'm closing this issue due to a lack of information. If you are the original filer of this issue and still encounter this problem, feel free to reopen this issue. If you're not the original filer of this issue, please open a new issue instead.
