### ISSUE TITLE
SteamVR and OSVR don't play well if you use a funky resolution

### ISSUE THREAD

**Issue by joejoejoey04** [OSVR/SteamVR-OSVR#39]
After a lot of hair pulling I found some sort of bug that completely stops OSVR functioning with Steamvr.

My main monitor has a standard resolution of 2560x1080 [21:9]. SteamVR simply will not work if I leave it set at that. Changing my resolution via Windows to standard 1080p doesn't fix it either... unless I go into nvidia's control panel and set the resolution from there. As soon as I did that steamvr immediately works.

Is this a bug or did I miss something between the compatibilities?

Thanks!

**Comment by toxicFork** [comment]
I wonder if the monitor resolutions and positions could be acquired
dynamically rather than reading from the config.

I think by default the config expects the main monitor to be 1920px exactly
and that the OSVR display is positioned at exactly right of the monitor
e.g. At coords 1920,0

**Comment by EzraBrooks** [comment]
@joejoejoey04 I had the same issue you did, as my main monitor is 3200x1800. You'll need to make a config file for the OSVR server that specifies the correct location for the OSVR window. In my case, I made a copy of `\bin\sample-configs\osvr_server_config.renderManager.sample.json` from the OSVR Core directory and changed `renderManagerConfig.renderManagerConfig.window.xPosition` to 3200 (in your case it should be 2560), and `renderManageConfig.renderManagerConfig.window.fullScreenEnabled` to true. From there you should be able to execute the OSVR server with the path to the new config file as a parameter and it should fix the problem.

**Comment by godbyk** [comment]
We recently updated the SteamVR-OSVR plugin to autodetect the resolutions and positions of the monitor and HMDs on your computer. Please try the latest version of the plugin with the latest released version of SteamVR and see if this resolves the problem. You should no longer need to manually set those values in the configuration file.
