### ISSUE TITLE
Visibility macros and compiler check

### ISSUE THREAD

**Issue by rpavlik** [OSVR/SteamVR-OSVR#4]
Looks like we just throw up our hands and say "not supported" unless using MSVC or GCC, even though I know Clang, and I imagine appleclang, provide the same attributes GCC does. Is this intentional for compatibility with SteamVR?

**Comment by d235j** [comment]
Can this be closed? Clang defines GNUC because it supports GNU extensions.

**Comment by godbyk** [comment]
@rpavlik Is this still the case or can this bug be closed?

**Comment by godbyk** [comment]
I'm not encountering this error. If it recurs, please reopen this issue. Thanks!
