### ISSUE TITLE
steamVR/OSVR Issue

### ISSUE THREAD

**Issue by Balderick** [OSVR/SteamVR-OSVR#40]
As a consumer user; running latest core, steamvr-osvr binaries, drivers, steam client and steamvr version, all i get is a white virtual world with mesh after starting steamVR.

What i did was after receiving my OSVR 1.3 dev kit the instructions on unboxing and set up were followed.  https://github.com/OSVR/OSVR-Docs/blob/master/Getting-Started/HDK/HDK-Unboxing-and-Getting-Started.md  The Tracker Viewer runs fine but i am struggling to manage which display gets used and still have not had the Palace demo or Team Fortress 2 (example/test in doc) run in the hmd.
The readme on https://github.com/OSVR/SteamVR-OSVR main page were followed for installing and testing steamVR.   

What i am trying to do is be able to play vr content in steam games/apps using OSVR hmd and tracking.

Some system specs: i7 6700k, 32GB ddr4 2666mhz, 6GB gtx 980 ti running windows 10 pro 64

Any useful advice would be welcomed and thanks in advance.

**Comment by godbyk** [comment]
Which configuration file are you using when you run the `osvr_server.exe`?

What is the resolution of your main monitor? What is the position of the HDK's display in relation to the main monitor?

What happens when you try to run a SteamVR game (e.g., TF2)?

**Comment by Balderick** [comment]
How do i confirm which configuration file are you using when you run the osvr_server.exe?

The resolution of my main monitor is 1920x1080 which is its native res.    The resolution of my hmd disply is 1920x1080 after following instruction in the Unboxing and Setup readme.  I have set the extended desktops and monitor as default display with OSVR hmd to right of desktop/screen.

I can not launch a steamvr game because i can only see a white virtual world in hmd.   If i launch TF2 game from desktop steam client what i get is just  a black screen on main monitor.  I can guess where the "quit" button is to exit though!

**Comment by godbyk** [comment]
@Balderick If you're not dropping a config file onto the `osvr_server.exe` or specifying it on the command line when you start the server, then it's using the default configuration file.

What do you see in the HMD when you try to run a SteamVR game?

Does the HMD show your Windows desktop background when not running SteamVR?

**Comment by Balderick** [comment]
Following the instructions here https://github.com/OSVR/OSVR-Docs/blob/master/Getting-Started/HDK/HDK-Unboxing-and-Getting-Started.md#get-osvr-server and at https://github.com/OSVR/SteamVR-OSVR#installation there is no mention of starting OSVR server from command prompt nor anything about specifying particular configuration files for osvr server or to enable the steamVR OSVR plugin/drivers.

To launch OSVR server i click the shortcut made; which is pinned to my task tray, for the osvr_server.exe which is locacted at C:\Users\Shaun\OSVR\OSVR server\OSVR-Core-Snapshot-v0.6-1120-gfc7433f-build246-vs12-64bit\bin\osvr_server.exe

After launching steamVR all i see in OSVR headset is a white virtual space with a mesh which i suspect is something to do with defining a virtual room related to steamvr room set up.

Yes.  Windows desktop is viewable in OSVR headset when steamVR is not running.

**Comment by godbyk** [comment]
Okay, it sounds like it's running with the default configuration which should work for your monitor's resolution.

The white room with the grid means that SteamVR has detected the HMD and is working okay.

You should be able to just start up a SteamVR game now.  

If the SteamVR game doesn't appear in the HMD or you encounter other problems, please let me know which game you're trying to run and any error messages you see.

**Comment by Balderick** [comment]
The display is no longer visible in nvidia control panel or windows settings > displays though devices shows the three osvr devices (box, hmd, camera) and there are no trouble devices in device manager.   Nothing happens in hmd now.

**Comment by godbyk** [comment]
It sounds like the HMD is running in _direct mode_. 

Disable direct mode by running `DisableOSVRDirectModeAMD.exe` or `DisableOSVRDirectModeNVidia.exe` (depending on your graphics card).

After that, the HMD should once again appear in the Windows display control panel.

**Comment by Balderick** [comment]
Okay.  So i got render manager installed to run that executable and have signs of life from headset again.    Realise now it is config file i need to work out next and am trying different samples in order to make custom config.   
How do i "run the optional beacon pre-calibration step"?.
Is the hdmi connection hot pluggable on hdk 1.3 hardware?.

**Comment by godbyk** [comment]
For now, let's skip the pre-calibration step. We can do that after we get SteamVR working. 

The HDK can be plugged in and unplugged while the computer is running. (Or did you mean something else by hot-pluggable?)

For the configuration file, you'll want to ensure you're using the extended version and disable direct mode.

**Comment by Balderick** [comment]
Yes that is what i intended to ask, just was not convinced plugging hdmi connectors into gpu's when machine was running was a good idea.   I found the instructions on how to reset hdk/display at https://github.com/OSVR/OSVR-user-settings#osvr-hdk-utilities-pane-provides

I couldn't work out to launch server with extended sample config so just renamed it osvr_server_config after renaming the original json with same name and am now starting server by "osvr_server osvr_server_config.json" from command prompt.

All that i can see in hdk display is windows extended desktop but it is bright green instead of bright blue.  (using default win 10 background)

**Comment by Balderick** [comment]
I am really struggling to get the same thing to happen twice on disconnecting and reconnecting hdk due to a pooorly designed usb coonection/cable management on hdk audio/belt box.   That is why i am struggling to set up hdk and use hdk.

**Comment by Balderick** [comment]
@godbyk okay let's start from https://github.com/OSVR/SteamVR-OSVR/issues/40?_pjax=%23js-repo-pjax-container#issuecomment-194483230 again.

> Which configuration file are you using when you run the osvr_server.exe?
I am launching osvr_server from command prompt using osvr_server sample-configs\osvr_server_config.HDK13ExtendedLandscape.sample.json

> What is the resolution of your main monitor? What is the position of the HDK's display in relation to the main monitor?
Display 2 is monitor using 1920x1080 and is primary display.  Display 1 is hdk display and it too is using 1920x1080.  Desktops are extended.

> What happens when you try to run a SteamVR game (e.g., TF2)?  On primary display I get the steamVR status app showing hdk display is connected but not ready with an icon in system tray showing steamvr is running.   There is also a compositor icon on task bar indicating a steam vr compositor window is running.   tbc

**Comment by Balderick** [comment]
The update for OSVR Control seems to have shown a firmware update that is available but did not get installed when i updated on initial set up.  Updating system firmware from 1.8.4 to 1.9.1 has made a huge difference.   testing ...

**Comment by godbyk** [comment]
I wanted to touch base and see if you were still experiencing any problems with OSVR and SteamVR.

**Comment by Balderick** [comment]
I have been battling hardware issues that are cause of not being able to use my machine nevermind the hdk!;  ...     ... You know you have bleeding edge tech when your mobo is receiving bios updates on a fortnightly basis, right?

Long story short I just updated my firmware for mobo today again and am now in longest, slickest, bestest running desktop session I ever had on this build so hope am on right track to lose me VR cherry.

I am pretty sure this issue can be closed.   Will update regardless.

**Comment by Balderick** [comment]
Just found what I have been waiting for https://www.reddit.com/r/OSVR/comments/4hxwve/psa_latest_nvidia_drivers_36510_once_again/
and understand I need to be applying the broken steamvr beta 1234x3 workaround described at https://www.reddit.com/r/OSVR/wiki/steamvr

Looking forward too trying again ...

**Comment by d235j** [comment]
@Balderick the workaround should no longer be necessary with the latest version of SteamVR and the latest build of SteamVR-OSVR.

**Comment by Balderick** [comment]
@d235j Can now confirm osvr core 73 and latest steamVR-OSVR drivers still do not launch steam games (only tried Dirt rally and TF2 so far) but steamvr's behaviour with my set up is peculiar.   

Running mobo with igpu giving intel 530  which is where my primary display is connected to along with a gtx 980ti using latest drivers and is connected to osvr hdk.    Steam client gets moved to hdk display and it is still running in large mode, is non fullscreen and upside down.   Disconnecting power and usb at audio/belt box and a system reboot is needed for steam client to show on primary display again.

Tracker view seems to be working as expected and palace demo nearly works, but it too, is upside down in hdk display.

**Comment by stephenmsnow** [comment]
I am a partnered developer who's been hoping to get the time to jump in and
start working on this platform since getting my headset months ago... but
with deadlines and issues at my day job, I've barely been able to touch the
unit since I got it... I've had varying degrees of success in the all too
few times I've had to actually attempt to work with the unit since I
received it... I've tried compiling myself from code vs nightly builds with
the same results, Steam keeps changing their API which seems to mean that
the OSVR hackers have to keep working around new additions and deprecating
code with each successive release.

Basically, what I'm asking now, since I finally have some time... is where
are we at now? I'm finally getting to the point where a little bit of free
time is something I have, and I don't want to waste my limited time working
on something pointless.  I very much believe that SteamVR is probably the
most important thing to have working right now, since that's where most of
the content is going to be... especially since VR experiences in the source
engine are far less resource-intensive than anything I've seen in the unity
or unreal engines (we have vives, rifts, and the HDK here at my work).

Could I be of assistance on the SteamVR compatibility side?  If not, where
would a video game programmer by day be most useful jumping in right now
with limited time to offer, at least for the next 2 months, after which I
should have MUCH more time available (adding a major feature to our engine
has been a much longer and more drawn out process than I'd anticipated
originally) :P

**Comment by Balderick** [comment]
Running verify cache for steamvr fixed the missing drivers.cfg.

**Comment by Balderick** [comment]
So running latest nvidia, steamvr-osvr drivers on current latest osvr runtime with steamvr (no betas) have for the first time had the video option in TF2 to enable virtual reality; however, when restarting game to apply the option the game defaults to disabling virtual reality likely due to no steamvr compositor running as shown in the imgur screenie i shared in a post above.

**Comment by Balderick** [comment]
The only way the option to enable virtual reality in TF2 video settings to appear is by using -vr launch option.

**Comment by Balderick** [comment]
After making sure the 4k tv being as primary display is using 1080 res now get steam compositor starting without error however when i try to launch TF" i now get a warning telling me TF2 does not support VR.   It looks like this http://imgur.com/Y8Y3KMH

**Comment by Balderick** [comment]
So having worked through all known workarounds for all the issues my hdk display now only ever shows green stuff.

I have given up on this one until i can afford another hdk or any other suitable known working option.

**Comment by rpavlik** [comment]
If all you see is green in your hdk, file a support ticket at http://support.osvr.com because that sounds like a hardware defect

**Comment by Balderick** [comment]
Thanks for that reminder and suggestion @rpavlik.  After waiting more than five working days for a response from razers support portal that option will hopefully prove very useful.
