### ISSUE TITLE
Use of vrpathreg?

### ISSUE THREAD

**Issue by rpavlik** [OSVR/SteamVR-OSVR#41]
I hadn't seen this tool when trying SteamVR earlier, but it showed up in a semi-recent version apparently:

```
C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64>vrpathreg --help
Commands:
  show - Display the current paths
  setruntime <path> - Sets the runtime path
  setthis - Sets the runtime path to the runtime that vrpathreg lives in
  setconfig <path> - Sets the config path
  setlog <path> - Sets the log path
  adddriver <path> - Adds an external driver
  removedriver <path> - Removes an external driver
```

Might let us have a nicer install experience by using the `adddriver` command.

**Comment by bdone2012** [comment]
Hey @rpavlik I'm trying to use Psmove controllers with the rift CV1 through OSVR so I can play Steam VR games with motion controls. My controllers work properly in tracker viewer but I can't get them to show up in Steam VR. I've added { ... "steamvr" : { "activateMultipleDrivers" : true } } and "requireHmd": false. So I think my problem is registering it with the Steam VR runtime. I've tried vrpathreg adddriver C:\Program Files(x86)\Steam VR PSMove driver\ psmove but when I do vrpathreg show all I get is the hydra driver. 

![image](https://cloud.githubusercontent.com/assets/6579647/14932502/45942a0c-0e45-11e6-94c4-899817731ac0.png)

My vrserver.txt looks like this http://imgur.com/LVZb9N4
Thanks

**Comment by godbyk** [comment]
I put together a [`SteamVRPaths.cmake` script](https://github.com/OSVR/SteamVR-OSVR/blob/config/cmake/SteamVRPaths.cmake) that seems to work well in OS X and Linux. I haven't tested it in Windows yet.

I'll merge it in after finishing some config file work and more testing.

**Comment by bdone2012** [comment]
Ah thanks. I had something wrong with my plugin. I got it working now.

**Comment by godbyk** [comment]
Running `make install` now installs the plugin to the prefix path you specify and automatically runs `vrpathconfig` to point it to the location of the driver.

**Comment by rpavlik** [comment]
README still isn't updated, though...
