### ISSUE TITLE
Driver not working with latest SteamVR and OSVR version

### ISSUE THREAD

**Issue by g00pix** [OSVR/SteamVR-OSVR#44]
Hello,
the drivers are not working with the last version of SteamVR, OSVR Server and the plugin.

Here is the error : http://i.imgur.com/azQc3QE.png

**Comment by d235j** [comment]
@g00pix: is your HMD working with properly with OSVR software/games/demos?

**Comment by godbyk** [comment]
@g00pix Could you give the latest build of the SteamVR-OSVR driver a try? I've updated it to work with the latest released version of OpenVR (v1.0.0) and it works for me with the latest released version (non-beta) of SteamVR. I haven't tried it with a beta release of SteamVR yet.
