### ISSUE TITLE
Missing tracking API calls

### ISSUE THREAD

**Issue by nanospork** [OSVR/SteamVR-OSVR#45]
Thought it was time to formally open an issue for this.

With the latest SteamVR driver and most recent functional version of SteamVR (last I've tested was beta v1457503340, but I believe it happens with the current release version as well), the room setup does not complete successfully. Even when a player defines the floor height, the height always appears to be interpreted directly from the OSVR vertical axis.

In addition, the recentering controls in the Settings do not function at all. Similarly, players of Elite Dangerous have found that the recentering keybind does not work in Elite: Dangerous either, and in addition Elite is subject to a number of graphical glitches that appear to be induced by faulty head tracking. For example, parts of the HUD may rapidly jump between rendering as if from above and rendering as if from straight ahead.

@d235j suggested that these issues, seemingly related to positional tracking, may be due to API-calls/property-requests/other-functionality that are not yet implemented in the driver.

**Comment by njbmartin** [comment]
> parts of the HUD may rapidly jump between rendering as if from above and rendering as if from straight ahead

The same is true during the final step of Room Setup.

No matter what value is entered into the height property during setup, the camera in the living room scene would be positioned at Y:0, clipping the floor.

It also seems that there is no way to proceed past this step, possibly because the camera is positioned at zero.

It also seems as though the Room Setup is very heavily dependant on Vive and the controllers, despite specifying the "Standing" option instead of "Room Scale". Not sure if this has always been the case as I've only just tried it.

This is using the latest version of Steam, SteamVR and all the OSVR related stuff.

**Comment by nanospork** [comment]
Possibly related to these issues is a glitch whereby the screen appears to flicker - when viewed in slow motion, it seems that for just a frame or two the view is rotated (yaw) some significant distance, and afterwards it resumes normal tracking operation.

There is also occasionally a glitch in Elite: Dangerous in which the orientation the game uses for culling does not match the rendering orientation. In other words, geometry is clipped or culled even within the player's view. This one seems to be especially prevalent if the user does not keep the headset in approximately the same position while starting the OSVR Server, SteamVR, and Elite. For example, if the user rotates the headset between starting SteamVR and Elite, then uses osvr_reset_yaw.exe to fix the offset, this glitch will sometimes appear.

**Comment by punkerich** [comment]
Video proof of said glitch:
[https://www.youtube.com/watch?v=cFyH9akrxcI&feature=youtu.be](url)

Picture of captured frame:
[http://www.silicondroid.com/osvr/reddit/glitch.jpg](url)

**Comment by djdevin** [comment]
> It also seems as though the Room Setup is very heavily dependant on Vive and the controllers

I actually had a DK1 (non-OSVR at the time) and room setup was fine. Now I have the HDK 1.3 with working hydras, the only killer right now is that player height. IR tracking makes it slightly better but it's still only a foot off of the VR ground.

**Comment by punkerich** [comment]
atm i'm running latest core, 1186, with steamvr 340. what i noticed today after another test (ED patched, new crimson beta): the jumpy tracking is far less worse when another window is active, e.g. osvr control (forgot to activate ED again). as soon as i'm back in ED it gets terrible. Found something more curious, when you look at this vid: https://www.youtube.com/watch?v=Y7YNdhOfkiE at around 3:20 you can clearly see the same flickering i posted in my vid. BUT. it only seems to be in the menu here. look at 8:30 and onwards. no jumpy tracking, no flickering. only thing i could see is that he's using an even older steamvr, 1456770167, and a very old core, 1114.

**Comment by godbyk** [comment]
We recently updated the SteamVR-OSVR plugin to allow it to complete room setup, enable direct mode, and experience improved tracking. Please try the latest version of the plugin with the latest released version of SteamVR and see if this resolves the problem.
