### ISSUE TITLE
SteamVR - Work around applied, Dual images in each eye.

### ISSUE THREAD

**Issue by Xenofiler** [OSVR/SteamVR-OSVR#49]
Hi all, I just recently received my OSVR and have learned alot in the last week. I however would like to try an use some SteamVR software to see if it is worth my time. I have followed all the tutorials and installed all drivers, updated config files and the like. So here's the deal. 

Start osvr_server.exe (works great)
Start Steam VR software (works as expected)
Start Steam VR supported software, images come to HDK however both eyes get the side by side side view and each eye is not getting its own image separately. 

I cant seem to find a good tutorial or figure out the KeyWords on how to get this fixed. Any assistance, maybe I missed a config somewhere?

I have set the osvr_server_config.HDK13ExtendedLandscape.sample to the default config file. I really appreciate you all taking the time to look at this.

**Comment by maso27** [comment]
I'm encountering this issue too.
Up until last Wednesday I had everything working great, then Steam did a mandatory update of SteamVR and broke everyone's HDK's.  As far as I know the devs are still working around the clock to rectify the problem.

**Comment by Xenofiler** [comment]
No worries. I didn't see any other posts regarding the double image in both eyes issue and was having trouble finding a good KeyWord to look at it. If I figure out a fix, I will post it immediately. I do have a few ideas I want to try tonight. l'll let you know how it goes.

**Comment by maso27** [comment]
I spent a few minutes working on this tonight, and it turns out that SteamVR is working again.
My issue was that I hadn't downloaded SteamVR-OSVR build v0.1-100 yet.
But have you done the following:

1.) Implemented the "Steam VR Driver Fix" [here](https://www.reddit.com/r/OSVR/comments/4he17n/steam_vr_driver_fix_02052016_ddmmyy/)
2.) Tried toggling Side-by-Side mode in "OSVR Control"

Those things helped me.

**Comment by d235j** [comment]
@maso27 that fix should not be necessary with the latest SteamVR-OSVR driver.
@Xenofiler can you check the settings in OSVR Control?

**Comment by Xenofiler** [comment]
@d235j Im assuming that you meen the OSVR-config.exe that brings up the nice browser based interface? it is currently setup using
`OSVR_HDK_1_3.json	Specific to the optics of 1.3, with Render Manager compatible distortion parameters	HDK	OSVR	1.3`

Rendering is 
`{
  "directModeEnabled": false,
  "directDisplayIndex": 0,
  "directHighPriorityEnabled": true,
  "numBuffers": 2,
  "verticalSyncEnabled": true,
  "verticalSyncBlockRenderingEnabled": true,
  "renderOverfillFactor": 1.5,
  "renderOversampleFactor": 1,
  "window": {
    "title": "OSVR",
    "fullScreenEnabled": true,
    "xPosition": 1920,
    "yPosition": 0
  },
  "display": {
    "rotation": 0,
    "bitsPerColor": 8
  },
  "prediction": {
    "enabled": true,
    "staticDelayMS": 48,
    "leftEyeDelayMS": 7.5,
    "rightEyeDelayMS": 0,
    "localTimeOverride": true
  },
  "timeWarp": {
    "enabled": true,
    "asynchronous": false,
    "maxMsBeforeVSync": 5
  }
}`

And no plugins enabled. 
Maybe i continue to miss something?

**Comment by d235j** [comment]
@Xenofiler no, I'm referring to the "OSVR HDK control software and firmware upgrade tool" available at http://osvr.github.io/using/.

**Comment by Xenofiler** [comment]
@d235j 
#?v
Version 1.92  Mar 24 2016

Tracker:1.8.4.415

**Comment by d235j** [comment]
@Xenofiler Can you try clicking the "Toggle side-by-side" button?

**Comment by Xenofiler** [comment]
@d235j I did try that, it made no difference to the image except in extended mode when it moved the image to one eye only. In normal extended mode while looking at the desktop everything is showing fine with no duplicate images in both eyes, just the normal stereoscopic.

**Comment by Xenofiler** [comment]
fixed. The toggle side-by-side has to be completed via OSVR-Control while the server is not running. This will cause the desktop image to look funky but does fix the issue of seeing double in Steam apps. @d235j Thanks for all your help. Awesome Job.
