### ISSUE TITLE
Room Setup Connection Loss - SteamVR-OSVR-Win-Build-v0.1-170-g09dc772-core-v0.6-1194-g0c54f5e

### ISSUE THREAD

**Issue by Proxishh** [OSVR/SteamVR-OSVR#60]
Hey guys, 

I've tried out the new SteamVR driver and it seems to be working well. 
I can confirm I've gotten it to work in direct mode. 
Setup required a .json replacement with the directmode.json and a restart for it to take effect.

The only issue I'm having, is that Room Setup is still kicking up a fuss. When running games normally, things are running fine (feels like better than before tbh) but when running room setup, the connection is dropping every 4-6 seconds.

I was still able to the initial room setup procedure and get to the "put your headphones and HMD on now", at which point, when loaded into the livingroom, the OSVR would lose connection to SteamVR and jutter in one direction for half a second then reset it's position.
After roughly a minute, Room Setup just crashed.

I have the SteamVR output log below. If you require a video demonstration of the issue I'm running into, let me know and I'll setup the camera.

[output_log.txt](https://github.com/OSVR/SteamVR-OSVR/files/293815/output_log.txt)

**Comment by demonixis** [comment]
Hi,

I've the connection issue in Unity using OpenVR too..

**Comment by godbyk** [comment]
We recently updated the SteamVR-OSVR plugin to allow it to complete room setup. Please try the latest version of the plugin with the latest released version of SteamVR and see if this resolves the problem.
