### ISSUE TITLE
LibreVR/Revive = SteamVR Unresponsive - SteamVR-OSVR-Win-Build-v0.1-170-g09dc772-core-v0.6-1194-g0c54f5e

### ISSUE THREAD

**Issue by Proxishh** [OSVR/SteamVR-OSVR#61]
Hey guys, 

Unfortunately, even though the new driver now works with the latest version of Steam, when trying to use Revive, SteamVR is going unresponsive and the OSVR display turns half light blue and half dark blue.

**Comment by godbyk** [comment]
Could you explain what you're trying to achieve? What game are you trying to play? Is it a SteamVR game? Which HMD are you trying to use?

Thanks!

**Comment by Proxishh** [comment]
Sorry I didn't get back to you sooner.

I was trying to get War Thunder to work via Revive. It now does after the most recent update from you guys.

Fantastic job.

**Comment by godbyk** [comment]
Glad to hear it! Thanks for letting me know.
