### ISSUE TITLE
SteamVR Compositor no longer works in extended mode

### ISSUE THREAD

**Issue by gothickitty93** [OSVR/SteamVR-OSVR#65]
For some reason, after installing the updated plugin, and updating SteamVR, extended mode won't work (error 400, 109), but direct mode does work. I already did the fix for the different main monitor resolution, and have them positioned correctly This means that TF2, HL2, HL:S... won't work in VR, as they don't support direct mode.

**Comment by HelenXR** [comment]
I also have the same one, how do you deal with, thank you for your help！
