### ISSUE TITLE
vrserver crashes repeatedly, but only with some games

### ISSUE THREAD

**Issue by djdevin** [OSVR/SteamVR-OSVR#66]
Some games are fine - Abbot's Book, Colosse, The Cubicle, The Rose and I, The Night Cafe. Direct mode works fine.

But some games will start for a few seconds and then vrserver starts to crash repeatedly. This includes The Lab, Skeet VR. Every time it does it flicks back to the compositor room, then back into the game. The game doesn't restart, it just looks like it glitches back and forth. It does this for a while until it finally crashes. I can't seem to figure this out. Unfortunately I don't have another headset to test if it is just my machine or SteamVR-OSVR. I'm thinking maybe it has to do with games that have Vive-specific code, which makes sense if The Lab and others crash.

Output from vrserver.txt:

```
Thu Jun 09 2016 19:48:54.553 - New Connect message from S:\Program Files (x86)\Steam\steamapps\common\Spell Fighter VR\SpellFighter.exe (VRApplication_Scene) 6236 
Thu Jun 09 2016 19:48:54.553 - Setting app steam.app.455440 PID to 6236
Thu Jun 09 2016 19:48:54.553 - Using existing HMD osvr.OSVR HDK
Thu Jun 09 2016 19:48:55.864 - IPCPipe(SpellFighter (6236)): Process disconnected.
Thu Jun 09 2016 19:48:55.864 - Process SpellFighter (6236) disconnected
Thu Jun 09 2016 19:48:55.924 - New Connect message from S:\Program Files (x86)\Steam\steamapps\common\Spell Fighter VR\SpellFighter.exe (VRApplication_Scene) 6236 
Thu Jun 09 2016 19:48:55.924 - Setting app steam.app.455440 PID to 6236
Thu Jun 09 2016 19:48:55.924 - Using existing HMD osvr.OSVR HDK
Thu Jun 09 2016 19:49:01.628 - IPCPipe(SpellFighter (6236)): Process disconnected.
Thu Jun 09 2016 19:49:01.628 - Process SpellFighter (6236) disconnected
Thu Jun 09 2016 19:49:01.695 - New Connect message from S:\Program Files (x86)\Steam\steamapps\common\Spell Fighter VR\SpellFighter.exe (VRApplication_Scene) 6236 
Thu Jun 09 2016 19:49:01.695 - Setting app steam.app.455440 PID to 6236
Thu Jun 09 2016 19:49:01.695 - Using existing HMD osvr.OSVR HDK
Thu Jun 09 2016 19:49:06.090 - IPCPipe(finalCandidate1 (8744)): Process disconnected.
Thu Jun 09 2016 19:49:06.090 - Process finalCandidate1 (8744) disconnected
Thu Jun 09 2016 19:49:07.146 - IPCPipe(SpellFighter (6236)): Process disconnected.
Thu Jun 09 2016 19:49:07.146 - Process SpellFighter (6236) disconnected
Thu Jun 09 2016 19:49:07.213 - New Connect message from S:\Program Files (x86)\Steam\steamapps\common\Spell Fighter VR\SpellFighter.exe (VRApplication_Scene) 6236 
Thu Jun 09 2016 19:49:07.213 - Setting app steam.app.455440 PID to 6236
Thu Jun 09 2016 19:49:07.213 - Using existing HMD osvr.OSVR HDK
Thu Jun 09 2016 19:49:21.060 - IPCPipe(SpellFighter (6236)): Process disconnected.
Thu Jun 09 2016 19:49:21.060 - Process SpellFighter (6236) disconnected
Thu Jun 09 2016 19:51:36.362 - Processing message Unknown VRMsgType (0) from Steam (6376) took 0.0131 seconds
```
And so on.

Output from a game log:
```
[VRDevice] Successfully created device OpenVR.
OpenVR Shutdown
 
(Filename:  Line: 627)

OpenVR initialized!
 
(Filename:  Line: 315)

HMD Vendor: osvr
HMD Model: OSVR HMD
HMD Render Model: generic_hmd
HMD Serial Number: OSVR HDK
 
(Filename:  Line: 338)

[VRDevice] Successfully created device OpenVR.
OpenVR Shutdown
 
(Filename:  Line: 627)

OpenVR initialized!
 
(Filename:  Line: 315)

HMD Vendor: osvr
HMD Model: OSVR HMD
HMD Render Model: generic_hmd
HMD Serial Number: OSVR HDK
```

Eventually ends in:

```

Error occurred at 2016-06-09_194910.
S:\Program Files (x86)\Steam\steamapps\common\Spell Fighter VR\SpellFighter.exe, run by Devin2.
41% memory in use.
8094 MB physical memory [4758 MB free].
16286 MB paging file [11251 MB free].
134217728 MB user address space [134216704 MB free].
Write to location fd363530 caused an access violation.
```

Radeon R9 290, tried with stable + beta drivers.

**Comment by jasoncoan** [comment]
I'm getting this same issue with the Unity Editor 5.40b17. Skeet VR, Spell Fighter, and most of The Lab are built with Unity, so maybe it's an issue with Unity?

**Comment by jasoncoan** [comment]
I've done further testing into this. Bigscreen, another Unity game, doesn't have this issue at all. Bigscreen is built with Unity 5.3.4p1, whereas The Lab, Skeet VR, and Spell Fighter are all built with some version of the Unity 5.4 beta. 

It doesn't appear to be an issue with OpenVR versions, as downgrading to version 0.9.19 (Bigscreen's version as far as I can tell) either does nothing to fix the issue or crashes the game.

Unity 5.4 included native integration with OpenVR, so I can only guess that it has something to do with how Unity 5.4 integrates with OpenVR it not liking the OSVR driver.

**Comment by djdevin** [comment]
Full logs of every logfile touched 

[vrclient_Skeet.txt](https://github.com/OSVR/SteamVR-OSVR/files/313015/vrclient_Skeet.txt)
[configstore_log.txt](https://github.com/OSVR/SteamVR-OSVR/files/313013/configstore_log.txt)
[vrcompositor.txt](https://github.com/OSVR/SteamVR-OSVR/files/313018/vrcompositor.txt)
[vrserver.txt](https://github.com/OSVR/SteamVR-OSVR/files/313014/vrserver.txt)
[content_log.txt](https://github.com/OSVR/SteamVR-OSVR/files/313017/content_log.txt)
[vrclient_vrmonitor.txt](https://github.com/OSVR/SteamVR-OSVR/files/313016/vrclient_vrmonitor.txt)
[cloud_log.txt](https://github.com/OSVR/SteamVR-OSVR/files/313019/cloud_log.txt)

These are all from Steam/Logs

These are the ones from the game crash dump folder:

[2016-06-13_220720.zip](https://github.com/OSVR/SteamVR-OSVR/files/313023/2016-06-13_220720.zip)

**Comment by djdevin** [comment]
This seems to be fixed in the latest SteamVR beta. I was able to launch SkeetVR, The Lab, and the SteamVR tutorial without the glitching issue.

Reverting back to an earlier beta reproduces the problem immediately, so I'd say this issue is fixed.

**Comment by godbyk** [comment]
I'm happy to let SteamVR take the blame for this. :-)

If it does recur, however, feel free to reopen this issue. Thanks!
