### ISSUE TITLE
Switching Between Extended and Direct Requires steamvr.vrsettings Deletion

### ISSUE THREAD

**Issue by Proxishh** [OSVR/SteamVR-OSVR#67]
Hey Guys, 

Having a bit of an issue with the OSVR/SteamVR driver when it comes to switching from Extended to Direct and vice versa.

I've been having to switch between Extended and Direct to try out a couple of applications and I now can't seem to get it working again and will most likely have to reinstall drivers if I can't figure out a method to get Direct Mode working again.

The previous workaround was to delete steamvr.vrsettings, disable Direct Mode, power cycle and restart, start server, start SteamVR, switch to Direct Mode, powercycle and restart and then things would work. Unfortunately, I can't seem to get this method working again...

Not sure what kind of info I can provide to help find a fix, but just let me know what you need to know and I'll get back to you asap.

NVidia Driver 368.39
Latest SteamVR Driver

EDIT: Figured out what was stopping the OSVR from connecting altogether, and it was that the OSVR wasn't positioned at 0 on the Y axis (aligned to the top of) beside my main monitor when in extended mode.

**Comment by Proxishh** [comment]
Sorry guys, it appears after further testing that a restart was needed after switching modes.

I'd tried restarting before and it wasn't working. I'm not sure what I was doing wrong before, but everything seems fine now after a restart.

**Comment by Balderick** [comment]
So there is no need to delete steamvr.vrsettings as described in your latest steamvr-osvr driver video tutorial?
