### ISSUE TITLE
Contents of distributed binaries

### ISSUE THREAD

**Issue by rpavlik** [OSVR/SteamVR-OSVR#79]
.lib files don't need to be distributed. Rather surprised they're being generated/installed at all - is the driver being added as a SHARED rather than a MODULE?

Also, if the steamvr.vrsettings file in the repo is important, it's not making it into the package ending up on bintray right now.

**Comment by godbyk** [comment]
The `driver_osvr` library is generated using `SHARED`.

The `steamvr.settings` file isn't important. It's there primarily for me to drop in optional configuration settings. It can be used as an example of what OSVR config settings are available, but doesn't need to be distributed or installed.

**Comment by godbyk** [comment]
I've corrected the `SHARED`/`MODULE` bit in the `update-v1.0.6` branch.

Thanks!
