### ISSUE TITLE
SteamVR does not detect HDK. Unable to load driver osvr because of error 103.

### ISSUE THREAD

**Issue by simkovic** [OSVR/SteamVR-OSVR#84]
I followed the [most recent guide](https://www.reddit.com/r/OSVR/comments/4yht13/osvr_recommended_quick_setup_guide_support_issue/) to set up HDK2 but when I run SteamVR I get 
"Headset not detected" error. vrserver.txt says:

Unable to load driver osvr from C:\Program Files (x86)\OSVR\OSVR-SteamVR\osvr\bin\win64
Unable to load driver osvr because of error 103. Skipping.

## System configuration

HDK2,  Windows 7, Nvidia optimus, Current all-in-one beta installer and I also tried the most recent 1320 SteamVR-OSVR version - no success.

[Here](https://www.reddit.com/r/OSVR/comments/4ydzl2/need_help_hdk_v14_steamvr_error_headset_not/) is another report from a user with HDK1 .

**Comment by godbyk** [comment]
@simkovic When I've encountered a error 103, it's usually because a required library (`.dll` file) is missing from the directory containing the `driver_osvr.dll` file. Or because a 32-bit library got mixed in with the 64-bit libraries or vice versa.

Could you test it again with the 1320 build (not the AIO build) and attach the `vrserver.txt` file?

You may need to uninstall the driver that came with the AIO installer so it doesn't interfere with the 1320 build.

Thanks!

**Comment by simkovic** [comment]
I renamed the old folder created by AIO at OSVR-SteamVR/osvr. I guess that counts as uninstall. I then  placed the osvr folder from the latest 1320 there. So it's 1320 only, no interference. And I get 103 again.

vrserver.txt:

`Sat Aug 20 2016 09:06:21.150 - VR server (v1469551863) starting up with config=C:\Program Files (x86)\Steam\config
Sat Aug 20 2016 09:06:21.150 - Using default values. No Json Settings available at C:\Program Files (x86)\Steam\config\steamvr.vrsettings
Sat Aug 20 2016 09:06:21.150 - Unable to read app config file from C:\Program Files (x86)\Steam\config\appconfig.json. No applications will be available
Sat Aug 20 2016 09:06:21.173 - New Connect message from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\tools\bin\win32\vrmonitor.exe (VRApplication_VRMonitor) 2332 
Sat Aug 20 2016 09:06:21.218 - lighthouse: Attached HID Devices:
Sat Aug 20 2016 09:06:21.219 - lighthouse:     No devices
Sat Aug 20 2016 09:06:21.219 -   driver lighthouse implements interfaces IVRSettings_001 ITrackedDeviceServerDriver_004 IVRDisplayComponent_002 IVRDriverDirectModeComponent_001 IVRControllerComponent_001 IVRCameraComponent_002 IServerTrackedDeviceProvider_003 IClientTrackedDeviceProvider_004 
Sat Aug 20 2016 09:06:21.219 - Loaded server driver lighthouse (IServerTrackedDeviceProvider_003) from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\driver_lighthouse.dll
Sat Aug 20 2016 09:06:21.219 - Driver lighthouse has no devices. Skipping
Sat Aug 20 2016 09:06:21.223 - error VRInitError_Driver_RuntimeOutOfDate when initing driver oculus from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\oculus\bin\win64\driver_oculus.dll.
Sat Aug 20 2016 09:06:21.223 - Unable to load driver oculus because of error 204. Skipping.
Sat Aug 20 2016 09:06:21.225 - error VRInitError_Driver_RuntimeOutOfDate when initing driver oculus_legacy from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\oculus_legacy\bin\win64\driver_oculus_legacy.dll.
Sat Aug 20 2016 09:06:21.225 - Unable to load driver oculus_legacy because of error 204. Skipping.
Sat Aug 20 2016 09:06:21.237 - Unable to load driver osvr from C:\Program Files (x86)\OSVR\OSVR-SteamVR\osvr\bin\win64\driver_osvr.dll.
Sat Aug 20 2016 09:06:21.237 - Unable to load driver osvr because of error 103. Skipping.
Sat Aug 20 2016 09:06:21.238 - error VRInitError_Init_HmdNotFound when initing driver null from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\null\bin\win64\driver_null.dll.
Sat Aug 20 2016 09:06:21.238 - Unable to load driver null because of error 108. Skipping.
Sat Aug 20 2016 09:06:21.238 - Active HMD not found. Returning best error VRInitError_Init_HmdNotFound
Sat Aug 20 2016 09:06:21.238 - Allowing driver load failure VRInitError_Init_HmdNotFound for application vrmonitor (2332) because it is vrmonitor
Sat Aug 20 2016 09:06:21.238 - Processing message VRMsg_Connect from vrmonitor (2332) took 0.0671 seconds`

**Comment by godbyk** [comment]
Let's see if we can figure out if it's just missing a DLL file.

1. Download [Dependency Walker](http://www.dependencywalker.com/) (it's free) and extract the files to the `C:\Program Files (x86)\OSVR\OSVR-SteamVR\osvr\bin\win64` directory.
2. Open a command prompt by holding down the **Windows key** on your keyboard and pressing the letter **R**. In the **Run** dialog box, type `cmd` and press **Enter**.
3. At the command prompt, type: `cd "C:\Program Files (x86)\OSVR\OSVR-SteamVR\osvr\bin\win64"` and press **Enter**. The command prompt should change to `C:\Program Files (x86)\OSVR\OSVR-SteamVR\osvr\bin\win64>`.
4. Type the following command and press **Enter**: `depends.exe /c /f:1 /u:1 /od:driver_osvr.dwi driver_osvr.dll`
5. Open a Windows Explorer window and navigate to `C:\Program Files (x86)\OSVR\OSVR-SteamVR\osvr\bin\win64`. Drag and drop the `driver_osvr.dwi` file into this issue to attach it.

Thanks!

**Comment by simkovic** [comment]
Indeed, d3dcompiler_47.dll and some other libraries appear to be missing. What is your suggestion on where to get those dlls? Google suggested Windows SDK, which I installed, but d3dcompiler_47.dll is still missing. Do I need to link the path somehow?

[driver_osvr.txt](https://github.com/OSVR/SteamVR-OSVR/files/428879/driver_osvr.txt)

**Comment by godbyk** [comment]
It does look like it might be missing `d3dcompiler_47.dll`.

This is shipped with Windows 8.1 by default, but not with Windows 7. We do include a copy in the installer, though, just not with the SteamVR-OSVR bundle, apparently—I'll have to look into fixing that.

You should be able to copy the `d3dcompiler_47.dll` file from `D:\Program Files (x86)\OSVR\***\bin` (where `***` is `SDK` or `Runtime`) to the `D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\osvr\bin\win32` folder. Similarly, copy the 64-bit version from `D:\Program Files\OSVR\***\bin` to `....\osvr\bin\win64`.

If you used the AIO installer, you can find a copy of the file in the `Program  Files/OSVR-SampleScene/OSVR_SampleScene_Data/Plugins/` directory.

**Comment by simkovic** [comment]
Cool, your suggestion worked. Thanks.
