### ISSUE TITLE
Losing Headset in Steam VR

### ISSUE THREAD

**Issue by nymVR** [OSVR/SteamVR-OSVR#94]
Hello,
whenever i look in the complete opposite direction of the camera (so it cant see the IR leds) my headset isnt shown in the steam vr status windows. In the main menu of steam vr it still tracks fine but when im ingame it just freezes or i can see my steamvr background. 
Any solutions?
Thank you

**Comment by godbyk** [comment]
The SteamVR-OSVR driver just passes along the tracking info we get from the OSVR server.

The solution to this problem will come from the OSVR-Core project. See https://github.com/OSVR/OSVR-Core/pull/448, for example.
